name: Docker images

on:
  push:
  pull_request:

jobs:
  images:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image: ['debian', 'fedora', 'ubuntu-22.04', 'ubuntu-24.04', 'ubuntu-wo-dependencies']
    steps:
    - uses: actions/checkout@main
    - name: Build and deploy
      uses: ./.github/actions/docker
      with:
        image: ${{ matrix.image }}
        repository: ${{ github.repository }}
        password: ${{ secrets.GITHUB_TOKEN }}
        event_name: ${{ github.event_name }}
        tag: ${{ github.sha }}
